/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AffectedVersionAttribution {
    #[serde(rename = "firstSeen", skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,
    #[serde(rename = "lastSeen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
}

impl AffectedVersionAttribution {
    pub fn new() -> AffectedVersionAttribution {
        AffectedVersionAttribution {
            first_seen: None,
            last_seen: None,
            source: None,
            uuid: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "NVD")]
    Nvd,
    #[serde(rename = "NPM")]
    Npm,
    #[serde(rename = "GITHUB")]
    Github,
    #[serde(rename = "VULNDB")]
    Vulndb,
    #[serde(rename = "OSSINDEX")]
    Ossindex,
    #[serde(rename = "RETIREJS")]
    Retirejs,
    #[serde(rename = "INTERNAL")]
    Internal,
    #[serde(rename = "OSV")]
    Osv,
    #[serde(rename = "SNYK")]
    Snyk,
    #[serde(rename = "TRIVY")]
    Trivy,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Source {
    fn default() -> Source {
        Self::Nvd
    }
}

