/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BomUploadResponse {
    /// Token used to check task progress
    #[serde(rename = "token")]
    pub token: uuid::Uuid,
}

impl BomUploadResponse {
    pub fn new(token: uuid::Uuid) -> BomUploadResponse {
        BomUploadResponse {
            token,
        }
    }
}

