/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependencyGraphResponse {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "purl", skip_serializing_if = "Option::is_none")]
    pub purl: Option<String>,
    #[serde(rename = "directDependencies", skip_serializing_if = "Option::is_none")]
    pub direct_dependencies: Option<String>,
    #[serde(rename = "latestVersion", skip_serializing_if = "Option::is_none")]
    pub latest_version: Option<String>,
}

impl DependencyGraphResponse {
    pub fn new() -> DependencyGraphResponse {
        DependencyGraphResponse {
            uuid: None,
            name: None,
            version: None,
            purl: None,
            direct_dependencies: None,
            latest_version: None,
        }
    }
}

