/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupedFinding {
    #[serde(rename = "vulnerability", skip_serializing_if = "Option::is_none")]
    pub vulnerability: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "attribution", skip_serializing_if = "Option::is_none")]
    pub attribution: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl GroupedFinding {
    pub fn new() -> GroupedFinding {
        GroupedFinding {
            vulnerability: None,
            attribution: None,
        }
    }
}

