/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IsTokenBeingProcessedResponse {
    #[serde(rename = "processing")]
    pub processing: bool,
}

impl IsTokenBeingProcessedResponse {
    pub fn new(processing: bool) -> IsTokenBeingProcessedResponse {
        IsTokenBeingProcessedResponse {
            processing,
        }
    }
}

