/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseGroup {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "licenses", skip_serializing_if = "Option::is_none")]
    pub licenses: Option<Vec<models::License>>,
    #[serde(rename = "riskWeight", skip_serializing_if = "Option::is_none")]
    pub risk_weight: Option<i32>,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl LicenseGroup {
    pub fn new(uuid: uuid::Uuid) -> LicenseGroup {
        LicenseGroup {
            name: None,
            licenses: None,
            risk_weight: None,
            uuid,
        }
    }
}

