/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    #[serde(rename = "licenseGroups", skip_serializing_if = "Option::is_none")]
    pub license_groups: Option<Vec<models::LicenseGroup>>,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "licenseText", skip_serializing_if = "Option::is_none")]
    pub license_text: Option<String>,
    #[serde(rename = "standardLicenseTemplate", skip_serializing_if = "Option::is_none")]
    pub standard_license_template: Option<String>,
    #[serde(rename = "standardLicenseHeader", skip_serializing_if = "Option::is_none")]
    pub standard_license_header: Option<String>,
    #[serde(rename = "licenseComments", skip_serializing_if = "Option::is_none")]
    pub license_comments: Option<String>,
    #[serde(rename = "licenseId", skip_serializing_if = "Option::is_none")]
    pub license_id: Option<String>,
    #[serde(rename = "isOsiApproved", skip_serializing_if = "Option::is_none")]
    pub is_osi_approved: Option<bool>,
    #[serde(rename = "isFsfLibre", skip_serializing_if = "Option::is_none")]
    pub is_fsf_libre: Option<bool>,
    #[serde(rename = "isDeprecatedLicenseId", skip_serializing_if = "Option::is_none")]
    pub is_deprecated_license_id: Option<bool>,
    #[serde(rename = "isCustomLicense", skip_serializing_if = "Option::is_none")]
    pub is_custom_license: Option<bool>,
    #[serde(rename = "seeAlso", skip_serializing_if = "Option::is_none")]
    pub see_also: Option<Vec<String>>,
}

impl License {
    pub fn new(uuid: uuid::Uuid) -> License {
        License {
            license_groups: None,
            uuid,
            name: None,
            license_text: None,
            standard_license_template: None,
            standard_license_header: None,
            license_comments: None,
            license_id: None,
            is_osi_approved: None,
            is_fsf_libre: None,
            is_deprecated_license_id: None,
            is_custom_license: None,
            see_also: None,
        }
    }
}

