/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedUser {
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "lastPasswordChange")]
    pub last_password_change: String,
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "suspended", skip_serializing_if = "Option::is_none")]
    pub suspended: Option<bool>,
    #[serde(rename = "forcePasswordChange", skip_serializing_if = "Option::is_none")]
    pub force_password_change: Option<bool>,
    #[serde(rename = "nonExpiryPassword", skip_serializing_if = "Option::is_none")]
    pub non_expiry_password: Option<bool>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<models::Team>>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<models::Permission>>,
    #[serde(rename = "newPassword", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
    #[serde(rename = "confirmPassword", skip_serializing_if = "Option::is_none")]
    pub confirm_password: Option<String>,
}

impl ManagedUser {
    pub fn new(last_password_change: String) -> ManagedUser {
        ManagedUser {
            username: None,
            last_password_change,
            fullname: None,
            email: None,
            suspended: None,
            force_password_change: None,
            non_expiry_password: None,
            teams: None,
            permissions: None,
            new_password: None,
            confirm_password: None,
        }
    }
}

