/*
 * Dependency-Track API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.11.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViolationAnalysisComment {
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "commenter", skip_serializing_if = "Option::is_none")]
    pub commenter: Option<String>,
}

impl ViolationAnalysisComment {
    pub fn new(timestamp: String, comment: String) -> ViolationAnalysisComment {
        ViolationAnalysisComment {
            timestamp,
            comment,
            commenter: None,
        }
    }
}

