name: Vulnerabilities-api CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Lint with Clippy
        run: make lint

      - name: Check formatting
        run: make fmt-check